// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: internal/judge/judge.proto

package judge

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JudgeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Language string   `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Input    []string `protobuf:"bytes,3,rep,name=input,proto3" json:"input,omitempty"`
}

func (x *JudgeRequest) Reset() {
	*x = JudgeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_judge_judge_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JudgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JudgeRequest) ProtoMessage() {}

func (x *JudgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_judge_judge_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JudgeRequest.ProtoReflect.Descriptor instead.
func (*JudgeRequest) Descriptor() ([]byte, []int) {
	return file_internal_judge_judge_proto_rawDescGZIP(), []int{0}
}

func (x *JudgeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *JudgeRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *JudgeRequest) GetInput() []string {
	if x != nil {
		return x.Input
	}
	return nil
}

type JudgeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Verdict []string `protobuf:"bytes,1,rep,name=verdict,proto3" json:"verdict,omitempty"`
	Stdout  []string `protobuf:"bytes,2,rep,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr  []string `protobuf:"bytes,3,rep,name=stderr,proto3" json:"stderr,omitempty"`
	Time    []int32  `protobuf:"varint,4,rep,packed,name=time,proto3" json:"time,omitempty"`
	Memory  []int32  `protobuf:"varint,5,rep,packed,name=memory,proto3" json:"memory,omitempty"`
}

func (x *JudgeResponse) Reset() {
	*x = JudgeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_judge_judge_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JudgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JudgeResponse) ProtoMessage() {}

func (x *JudgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_judge_judge_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JudgeResponse.ProtoReflect.Descriptor instead.
func (*JudgeResponse) Descriptor() ([]byte, []int) {
	return file_internal_judge_judge_proto_rawDescGZIP(), []int{1}
}

func (x *JudgeResponse) GetVerdict() []string {
	if x != nil {
		return x.Verdict
	}
	return nil
}

func (x *JudgeResponse) GetStdout() []string {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *JudgeResponse) GetStderr() []string {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *JudgeResponse) GetTime() []int32 {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *JudgeResponse) GetMemory() []int32 {
	if x != nil {
		return x.Memory
	}
	return nil
}

var File_internal_judge_judge_proto protoreflect.FileDescriptor

var file_internal_judge_judge_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6a, 0x75, 0x64, 0x67, 0x65,
	0x2f, 0x6a, 0x75, 0x64, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61,
	0x69, 0x6e, 0x22, 0x54, 0x0a, 0x0c, 0x4a, 0x75, 0x64, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61,
	0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x22, 0x85, 0x01, 0x0a, 0x0d, 0x4a, 0x75, 0x64,
	0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x64, 0x69, 0x63, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x64, 0x69, 0x63, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x64, 0x65, 0x72, 0x72, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x64, 0x65, 0x72, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x05, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f,
	0x72, 0x79, 0x18, 0x05, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79,
	0x32, 0x3b, 0x0a, 0x05, 0x4a, 0x75, 0x64, 0x67, 0x65, 0x12, 0x32, 0x0a, 0x05, 0x4a, 0x75, 0x64,
	0x67, 0x65, 0x12, 0x12, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x4a, 0x75, 0x64, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x4a, 0x75,
	0x64, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x30, 0x5a,
	0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x6f, 0x73, 0x68,
	0x6a, 0x6d, 0x73, 0x2f, 0x70, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x2d, 0x77, 0x61, 0x74, 0x63, 0x68,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6a, 0x75, 0x64, 0x67, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_judge_judge_proto_rawDescOnce sync.Once
	file_internal_judge_judge_proto_rawDescData = file_internal_judge_judge_proto_rawDesc
)

func file_internal_judge_judge_proto_rawDescGZIP() []byte {
	file_internal_judge_judge_proto_rawDescOnce.Do(func() {
		file_internal_judge_judge_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_judge_judge_proto_rawDescData)
	})
	return file_internal_judge_judge_proto_rawDescData
}

var file_internal_judge_judge_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_judge_judge_proto_goTypes = []interface{}{
	(*JudgeRequest)(nil),  // 0: main.JudgeRequest
	(*JudgeResponse)(nil), // 1: main.JudgeResponse
}
var file_internal_judge_judge_proto_depIdxs = []int32{
	0, // 0: main.Judge.Judge:input_type -> main.JudgeRequest
	1, // 1: main.Judge.Judge:output_type -> main.JudgeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_judge_judge_proto_init() }
func file_internal_judge_judge_proto_init() {
	if File_internal_judge_judge_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_judge_judge_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JudgeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_judge_judge_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JudgeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_judge_judge_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_judge_judge_proto_goTypes,
		DependencyIndexes: file_internal_judge_judge_proto_depIdxs,
		MessageInfos:      file_internal_judge_judge_proto_msgTypes,
	}.Build()
	File_internal_judge_judge_proto = out.File
	file_internal_judge_judge_proto_rawDesc = nil
	file_internal_judge_judge_proto_goTypes = nil
	file_internal_judge_judge_proto_depIdxs = nil
}
